#server:
#  tomcat:
#    threads:
#      max: 2000       # 최대 스레드 수
#      min-spare: 100  # 최소 대기 스레드 수


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/concurrency
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
#    lettuce:
#      pool:
#        max-active: 1000    # 최대 연결 수
#        max-idle: 200       # 대기 연결
#        min-idle: 50
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100

---
spring:
  config:
    activate:
      on-profile: server1

server: server1

---
spring:
  config:
    activate:
      on-profile: server2

server: server2