#server:
#  tomcat:
#    threads:
#      max: 10

spring:
  datasource:
#    hikari:
#      maximum-pool-size: 5
#      connection-timeout: 30000 # 커넥션을 기다리는 최대 시간(30초)
#    jdbc:mysql://localhost:3306/springtest?
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100

---
spring:
  config:
    activate:
      on-profile: server1

server: server1

---
spring:
  config:
    activate:
      on-profile: server2

server: server2